### ISSUE TITLE
MLT 7.0 Task List

### ISSUE THREAD

**Issue by bmatherly** [mltframework/mlt#655]
### Definite
- [x] link and chain for timing effects
- [x] remove mlt_geometry (convert anything affected to mlt_rect)
- [x] rename mlt_service_type enums to be like mlt_service_...
- [x] rename mlt_image_rgb24a as mlt_image_rgba
- [x] rename mlt_image_rgb24 as mlt_image_rgb
- [x] remove mlt_image_opengl
- [x] rename mlt_image_glsl as mlt_image_movit
- [x] rename mlt_image_glsl_texture as mlt_image_opengl_texture
- [x] remove the `height += 1` in mlt_image_format_size()
- [x] remove `mlt_transmitter` and variable argument lists in `mlt_events`
- [x] remove `mlt_frame.get_alpha_mask` function pointer
- [x] remove deprecated modules (dv, feeds, gtk2, kino, linsys, lumas, swfdec, videostab)
- [x] remove motion_est module
- [x] remove the core/data_feed and data_show filters
- [x] remove the core/region filter and and transition
- [x] merge vmfx module into plus
- [x] rename opengl module to movit
- [x] allow building the jackrack module in a LADSPA-only mode
- [x] add a mlt_image class
- [x] convert build completely to CMake

### Under Consideration
- [ ] add const and cleanup constructors in C++ API
- [ ] add option to build without locale
- [ ] mlt_profile -> mlt_context derived from mlt_properties, namely for reference-counting but also to replace mlt_environment()
- [ ] add color_trc, color_range, color_primaries, interpolation, and audio params (channels, frequency, channel_layout) to mlt_context
- [ ] tighten the property namespace (inconsistent service name prefixing, hiding, and putting things on mlt_frame)
- [ ] add mlt_rational type and property functions, and convert things like aspect ratios and frame rates to use it
- [ ] add 16-byte alignment for FFmpeg including aligned image plane and audio channel buffers
- [ ] change mlt_frame_get_image() to take mlt_image instead of multiple parameters (as well as get_image in all services)
- [ ] change mlt_frame_get_audio() to take mlt_audio instead of multiple parameters (as well as get_audio in all services)
- [ ] make more structures in framework more private

**Comment by ddennedy** [comment]
I have CMake in all of the non-SDK builds working (including macOS and msys2/Windows and briefly tested). That means we will adopt CMake and drop configure + make. However, I am not going to remove these immediately. Also, the Shotcut changes will not be merged immediately because its src.pro will require a CMake build of MLT (names of MLT dependencies changed to include "-7"). I need to get SDK builds working and my development workflow on macOS and Shotcut switched over and usable before then. This is just an update to say this is happening. Thanks @eszlari

**Comment by ddennedy** [comment]
I do not want any more major changes for v7. Going to merge to master now and stabilize for first release.
